

spring:
  datasource:
    dynamic:
      primary: pgsql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/new_vlinkage?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        pgsql:
          url: jdbc:postgresql://115.29.163.237:5432/vlkdj?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
          driver-class-name: org.postgresql.Driver
server:
  port: 80
